# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/segmentation_test',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/segmentation_test',
                'lib_path': 'segmentation_test'},
  'syms': {'segmentation_test.core': {'segmentation_test.core.foo': ('core.html#foo', 'segmentation_test/core.py')}}}
