# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_confg.ipynb.

# %% auto 0
__all__ = ['IMAGE_HEIGHT', 'IMAGE_WIDTH', 'EPOCS', 'BATCH_SIZE', 'BUFFER_SIZE', 'class_names', 'train_count', 'test_count',
           'num_classes', 'steps_per_epoch', 'validation_steps']

# %% ../nbs/01_confg.ipynb 3
IMAGE_HEIGHT = 224
IMAGE_WIDTH = 224
EPOCS = 5
BATCH_SIZE = 10
BUFFER_SIZE= 30
class_names = ['Pin']
train_count = 107
test_count = 27
num_classes = len(class_names)
steps_per_epoch = train_count // BATCH_SIZE
validation_steps = test_count // BATCH_SIZE

