# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_training.ipynb.

# %% auto 0
__all__ = ['SSIMLoss']

# %% ../nbs/10_training.ipynb 3
import torch 
from torch import nn
import pytorch_ssim

# %% ../nbs/10_training.ipynb 4
class SSIMLoss(nn.Module):
    def __init__(self, window_size=11, size_average=True, val_range=None):
        super(SSIMLoss, self).__init__()
        self.window_size = window_size
        self.size_average = size_average
        self.val_range = val_range

    def forward(self, img1, img2):
        return 1 - pytorch_ssim.SSIM()#ssim(img1, img2, window_size=self.window_size, size_average=self.size_average, val_range=self.val_range)



# %% ../nbs/10_training.ipynb 5
import nbdev; nbdev.nbdev_export('10_training.ipynb')
