# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_viz_utils.ipynb.

# %% auto 0
__all__ = ['show_model', 'view_image']

# %% ../nbs/03_viz_utils.ipynb 3
from tensorflow.keras.utils import plot_model
import matplotlib.pyplot as plt

# %% ../nbs/03_viz_utils.ipynb 4
def show_model(model, show_shapes=True, show_layer_names=True, to_file='model.png'):
    "Plot a Keras model as a graph."
    return plot_model(model, show_shapes=show_shapes, show_layer_names=show_layer_names, to_file=to_file)

# %% ../nbs/03_viz_utils.ipynb 5
def view_image(ds):
    image, label = next(iter(ds)) # extract 1 batch from the dataset
    image = image.numpy()
    label = label.numpy()
    
    fig = plt.figure(figsize=(22, 22))
    for i in range(20):
        ax = fig.add_subplot(4, 5, i+1, xticks=[], yticks=[])
        ax.imshow(image[i])
        ax.set_title(f"Label: {label[i]}")
