#ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "segmentation_test"
  site-url: "https://HasanGoni.github.io/segmentation_test"
  description: "Library for segmentation model"
  twitter-card: true
  open-graph: true
  repo-branch: main
  repo-url: "https://github.com/HasanGoni/segmentation_test"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/HasanGoni/segmentation_test"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
